name: Cypress test

on:
  push:
    branches: [ main ]
  pull_request:
    branches:  [ main ]
  workflow_dispatch:


jobs:
  test-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: run tests
        uses: cypress-io/github-action@v5

      - name: Run tests
        run: npm test
