name: Run Tests

on: 
  pull_request:
    branches: [main]
jobs:  
    ui-chrome-tests:
        runs-on: ubuntu-latest
        container:
            image: cypress/browsers:22.15.1
            options: --user 1001
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Install dependencies
              uses: npm install

            - name: "UI Tests - Chrome"
              uses: cypress-io/github-action@v6
              with:
                build: npx cypress info
                wait-on: "http://localhost:3000"
                wait-on-timeout: 120
                browser: chrome
                group: "Institucional - Chrome"
                spec: cypress/institucional/tests/*
                config-file: cypress.config.ts

