name: Cypress Tests

on:
    push: 
        branches: [ main ]
    pull_request:
        branches: [ main ]
    schedule:
        - cron: '0 18 * * 1,2,3,4,5'

jobs:  
    ui-chrome-tests:
        runs-on: ubuntu-latest
        container:
            image: cypress/browsers:22.15.1
            options: --user 1001
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Install dependencies
              uses: npm install

            - name: "UI Tests - Chrome"
              uses: cypress-io/github-action@v6
              with:
                build: npx cypress info
                wait-on: "http://localhost:3000"
                wait-on-timeout: 120
                browser: chrome
                group: "Institucional - Chrome"
                spec: cypress/institucional/tests/*
                config-file: cypress.config.ts